# Generated by Django 3.2.9 on 2021-12-17 14:01

import INV.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('PartNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to=INV.models.upload_image_path, verbose_name='عکس قطعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='قیمت')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Quantiti', models.CharField(blank=True, default=1, max_length=3, null=True, verbose_name='تعداد')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='محصول')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='کد محصول')),
                ('Tracebility_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='کد ردیابی')),
                ('description', models.TextField(blank=True, default=0, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='قیمت')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=500, size=[300, 250], upload_to=INV.models.upload_image_path, verbose_name='عکس محصول')),
                ('Instructions1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 750], upload_to=INV.models.upload_image_path, verbose_name='دستورالعمل ساخت 1')),
                ('Instructions2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 750], upload_to=INV.models.upload_image_path, verbose_name='دستورالعمل ساخت 2')),
                ('Quantiti', models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد')),
                ('BOM', models.ManyToManyField(to='INV.Part', verbose_name='قطعات')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
