# Generated by Django 3.2.9 on 2021-12-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='کد محصول'),
        ),
    ]
