# Generated by Django 3.2.9 on 2021-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='PartNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quantiti',
            field=models.CharField(blank=True, default=1, max_length=6, null=True, verbose_name='تعداد'),
        ),
    ]
