# Generated by Django 3.2.9 on 2021-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0003_auto_20211218_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان ')),
                ('Part', models.ManyToManyField(to='INV.Part', verbose_name='قطعه')),
                ('product', models.ManyToManyField(to='INV.Product', verbose_name='محصول ')),
            ],
        ),
    ]
