# Generated by Django 3.2.9 on 2021-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0004_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='CountPart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
