# Generated by Django 3.2.9 on 2021-12-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0005_bom_countpart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
