# Generated by Django 3.2.9 on 2021-12-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0006_delete_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان ')),
                ('CountPart', models.IntegerField(blank=True, null=True)),
                ('Part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INV.part', verbose_name='قطعه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INV.product', verbose_name='محصول ')),
            ],
        ),
    ]
