# Generated by Django 3.2.9 on 2022-01-01 05:54

import INV.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0007_bom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'قطعه', 'verbose_name_plural': 'قطعات'},
        ),
        migrations.RemoveField(
            model_name='bom',
            name='CountPart',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='Part',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='product',
        ),
        migrations.AddField(
            model_name='bom',
            name='PartNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد محصول'),
        ),
        migrations.AddField(
            model_name='bom',
            name='Quantiti',
            field=models.CharField(blank=True, default=1, max_length=3, null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='bom',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='bom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=INV.models.upload_image_path, verbose_name='عکس قطعه'),
        ),
        migrations.AddField(
            model_name='bom',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='bom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='BOM',
            field=models.ManyToManyField(to='INV.BOM', verbose_name='قطعات'),
        ),
    ]
