# Generated by Django 3.2.9 on 2022-01-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0008_auto_20220101_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BOM',
            field=models.ManyToManyField(to='INV.Part', verbose_name='قطعات'),
        ),
    ]
