# Generated by Django 3.2.9 on 2022-01-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0009_alter_product_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BOM',
        ),
        migrations.AddField(
            model_name='product',
            name='Parts',
            field=models.ManyToManyField(to='INV.Part', verbose_name='قطعات'),
        ),
    ]
