# Generated by Django 3.2.9 on 2022-01-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0010_auto_20220101_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='BOM',
            field=models.ManyToManyField(to='INV.BOM', verbose_name='BOM'),
        ),
    ]
