# Generated by Django 3.2.9 on 2022-01-01 06:27

import INV.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0011_auto_20220101_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BOM',
        ),
        migrations.AddField(
            model_name='bom',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=INV.models.upload_image_path, verbose_name='عکس قطعه'),
        ),
        migrations.AddField(
            model_name='bom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='bom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
