# Generated by Django 3.2.9 on 2022-01-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0012_auto_20220101_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BOM',
            field=models.ManyToManyField(to='INV.BOM', verbose_name='BOM'),
        ),
    ]
