# Generated by Django 3.2.9 on 2022-01-01 06:41

import INV.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0013_product_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('PartNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to=INV.models.upload_image_path, verbose_name='عکس قطعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='قیمت')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('Quantiti', models.CharField(blank=True, default=1, max_length=3, null=True, verbose_name='تعداد')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='BOM',
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
    ]
