# Generated by Django 3.2.9 on 2022-01-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0014_auto_20220101_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BOM',
            field=models.ManyToManyField(to='INV.BOMS', verbose_name='BOM'),
        ),
    ]
