# Generated by Django 3.2.9 on 2022-01-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0015_product_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Instructions1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Instructions2',
        ),
    ]
