# Generated by Django 3.2.9 on 2022-01-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0017_auto_20220101_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='BOM',
            new_name='BOMS',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Parts',
            new_name='Part',
        ),
    ]
