# Generated by Django 3.2.9 on 2022-01-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0018_auto_20220101_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BOMS',
            field=models.ManyToManyField(blank=True, to='INV.BOMS', verbose_name='BOM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Part',
            field=models.ManyToManyField(blank=True, to='INV.Part', verbose_name='قطعات'),
        ),
    ]
