# Generated by Django 3.2.9 on 2022-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0019_auto_20220101_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='PartNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد محصول'),
        ),
    ]
