# Generated by Django 3.2.9 on 2022-01-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0020_alter_part_partnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boms',
            options={'verbose_name': 'BOM', 'verbose_name_plural': 'BOMS'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='محصول'),
        ),
    ]
