# Generated by Django 3.2.9 on 2022-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0021_auto_20220102_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boms',
            name='name',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
