# Generated by Django 3.2.9 on 2022-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0022_auto_20220102_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boms',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='محصول'),
        ),
    ]
