# Generated by Django 3.2.9 on 2022-01-04 09:00

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0023_auto_20220102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Instructions1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path, verbose_name='دستورالعمل ساخت 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Instructions2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path, verbose_name='دستورالعمل ساخت 2'),
        ),
    ]
