# Generated by Django 3.2.9 on 2022-01-20 11:31

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0024_auto_20220104_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_10',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_12',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_13',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_8',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_9',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_Checking',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_Kafchini',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_LastTest_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_LastTest_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_LastTest_03',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_LastTest_04',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_LastTest_05',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_QC_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_QC_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
    ]
