# Generated by Django 3.2.9 on 2022-01-20 11:40

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0025_auto_20220120_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_1',
            new_name='_1_10',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_10',
            new_name='_1_11',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_12',
            new_name='_1_12',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_13',
            new_name='_1_13',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_2',
            new_name='_1_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_3',
            new_name='_1_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_4',
            new_name='_1_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_5',
            new_name='_1_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_6',
            new_name='_1_6',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_7',
            new_name='_1_7',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_8',
            new_name='_1_8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_9',
            new_name='_1_9',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_Checking',
            new_name='_1_Checking',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_Kafchini',
            new_name='_1_IT',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_LastTest_01',
            new_name='_1_Kafchini',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_LastTest_02',
            new_name='_1_LastTest_01',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_LastTest_03',
            new_name='_1_LastTest_02',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_LastTest_04',
            new_name='_1_LastTest_03',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_LastTest_05',
            new_name='_1_LastTest_04',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_QC_01',
            new_name='_1_LastTest_05',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_QC_02',
            new_name='_1_QC_01',
        ),
        migrations.AddField(
            model_name='product',
            name='_1_QC_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_10',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_11',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_12',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_13',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_8',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_9',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_Checking',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_IT',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_Kafchini',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_LastTest_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_LastTest_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_LastTest_03',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_LastTest_04',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_LastTest_05',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_QC_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_QC_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_image_path),
        ),
    ]
