# Generated by Django 3.2.9 on 2022-01-22 17:43

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0027_product__1_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_1_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_10',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_11',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_12',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_13',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_8',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_9',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_Checking',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_IT',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_Kafchini',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_LastTest_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_LastTest_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_LastTest_03',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_LastTest_04',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_LastTest_05',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_QC_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_1_QC_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_10',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_11',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_12',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_13',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_8',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_9',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_Checking',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_IT',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_Kafchini',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_LastTest_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_LastTest_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_LastTest_03',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_LastTest_04',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_LastTest_05',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_QC_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='_2_QC_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
    ]
