# Generated by Django 3.2.9 on 2022-02-07 14:34

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0029_auto_20220123_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_1_Boxing_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_Boxing_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
    ]
