# Generated by Django 3.2.9 on 2022-02-22 07:09

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0030_auto_20220207_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_1_Placing_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_Placing_02',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
    ]
