# Generated by Django 3.2.9 on 2022-04-04 09:20

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0031_auto_20220222_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_1_Repair_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_2_Repair_01',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
    ]
