# Generated by Django 3.2.9 on 2022-04-04 09:25

import INV.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('INV', '0032_auto_20220404_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_2_Repair_01',
            new_name='_2_Repair',
        ),
        migrations.RemoveField(
            model_name='product',
            name='_1_Repair_01',
        ),
        migrations.AddField(
            model_name='product',
            name='_1_Repair',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=INV.models.upload_Instructions_path),
        ),
    ]
