# Generated by Django 3.2.9 on 2021-12-17 14:09

import TRACING.models
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employ', '0001_initial'),
        ('INV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction_processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='مرحله ساخت ')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='کد')),
                ('Order', models.CharField(max_length=5, verbose_name='شماره مرحله ')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('Level', models.IntegerField(verbose_name='درجه اهمیت کار ')),
                ('guide', models.FileField(blank=True, null=True, upload_to=TRACING.models.upload_image_path, verbose_name=' دستورالعمل این مرحله ار OPC')),
            ],
            options={
                'verbose_name': 'مرحله ساخت ',
                'verbose_name_plural': 'مراحل ساخت ',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('code', models.CharField(max_length=20, null=True, unique=True, verbose_name='کد سفارش ')),
                ('Recive_Data', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان دریافت سفارش')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='تعداد سفارش')),
                ('MaximumTime', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='حد اکثر تاریخ تولید ')),
                ('Product', models.ManyToManyField(to='INV.Product')),
            ],
            options={
                'verbose_name': 'سفارش ',
                'verbose_name_plural': 'سفارش های فعال',
            },
        ),
        migrations.CreateModel(
            name='Recipt_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_product', models.CharField(default=True, max_length=100, verbose_name='کد محصول ')),
                ('description_prodact', models.TextField(default=True, verbose_name='شرح قطعه')),
                ('Qountiti', models.IntegerField(blank=True, default=True, verbose_name='تعداد')),
                ('order_code', models.IntegerField(blank=True, default=True, verbose_name='کد سفارش ')),
                ('curent_data', models.DateTimeField(blank=True, default=True, verbose_name='تاریخ ')),
                ('Cod_Operator', models.IntegerField(blank=True, default=True, verbose_name='کد اپراتور')),
                ('destinastion_store', models.CharField(blank=True, default=True, max_length=70, verbose_name='انبار مقصد')),
                ('sorce_store', models.CharField(blank=True, default=True, max_length=70, verbose_name='انبار مبدا')),
                ('form_number', models.IntegerField(blank=True, default=True, verbose_name='شماره حواله')),
                ('position_out', models.CharField(blank=True, default=True, max_length=50, verbose_name='نوع خروج')),
                ('center_cost', models.CharField(blank=True, default=True, max_length=70, verbose_name='مرکز هزینه ')),
            ],
            options={
                'verbose_name': 'حواله خروج',
                'verbose_name_plural': 'حواله های  خروج',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ایستگاه', max_length=20, unique=True, verbose_name='عنوان')),
                ('StationNumber', models.IntegerField(default=False, unique=True)),
                ('Active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاهای کاری ',
            },
        ),
        migrations.CreateModel(
            name='Sum_Recipt_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cod_SUM', models.CharField(blank=True, max_length=10, verbose_name='کد  محصول ')),
                ('DESCRIPTION', models.CharField(blank=True, max_length=70, verbose_name='شرح')),
                ('Sum_all_Pro', models.IntegerField(blank=True, verbose_name='جمع کل')),
                ('order_cod', models.IntegerField(blank=True, verbose_name='کد سفارش')),
                ('form_number', models.IntegerField(default=0, verbose_name='شماره حواله')),
            ],
            options={
                'verbose_name': 'جمع حواله خروج',
                'verbose_name_plural': ' جمع حواله های  خروج',
            },
        ),
        migrations.CreateModel(
            name='TracebilityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tracebility_code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='کد ردیابی')),
                ('Date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('time', models.TimeField(blank=True, null=True)),
                ('order', models.ManyToManyField(blank=True, to='TRACING.Orders', verbose_name=' سفارش')),
            ],
            options={
                'verbose_name': 'کد ردیابی',
                'verbose_name_plural': 'کد های ردیابی',
            },
        ),
        migrations.CreateModel(
            name='TracebilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator', models.CharField(blank=True, max_length=40, verbose_name='اپراتور')),
                ('Station', models.CharField(blank=True, max_length=40, verbose_name='ایسنگاه')),
                ('Order', models.CharField(blank=True, max_length=40, verbose_name='سفارش')),
                ('Product', models.CharField(blank=True, max_length=40, verbose_name='محصول')),
                ('tracebilityCode', models.CharField(blank=True, max_length=40, verbose_name='کد ردیابی')),
                ('Date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': ' ردیابی کد ',
                'verbose_name_plural': ' جدول ردیابی کد های    ',
            },
        ),
        migrations.CreateModel(
            name='TracebilityData_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator', models.CharField(blank=True, max_length=40, verbose_name='اپراتور')),
                ('Station', models.CharField(blank=True, max_length=40, verbose_name='ایسنگاه')),
                ('Order', models.CharField(blank=True, max_length=40, verbose_name='سفارش')),
                ('Product', models.CharField(blank=True, max_length=40, verbose_name='محصول')),
                ('tracebilityCode', models.CharField(blank=True, max_length=40, verbose_name='کد ردیابی')),
                ('Date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': ' ردیابی کد ',
                'verbose_name_plural': ' جدول ردیابی کد های    ',
            },
        ),
        migrations.CreateModel(
            name='Tracing_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', django_jalali.db.models.jDateField(default=0, verbose_name='تاریخ روز ')),
                ('Time', models.TimeField(default=0, verbose_name='زمان')),
                ('Operator', models.ManyToManyField(to='Employ.Person', verbose_name='اپراتور')),
                ('order', models.ManyToManyField(to='TRACING.Orders', verbose_name='سفارش')),
                ('product', models.ManyToManyField(to='INV.Product', verbose_name='محصول')),
                ('station', models.ManyToManyField(to='TRACING.Station', verbose_name='ایستگاه')),
                ('tracebility_code', models.ManyToManyField(to='TRACING.TracebilityCode', verbose_name='کد ردیابی')),
            ],
            options={
                'verbose_name': ' ردیابی قطعات ',
                'verbose_name_plural': ' جدول ردیابی قطعات   ',
            },
        ),
        migrations.CreateModel(
            name='Station_to_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_for_work', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع شفارس در خط تولید ')),
                ('StationNumber', models.ManyToManyField(default=0, to='TRACING.Station')),
                ('order', models.ManyToManyField(default=0, to='TRACING.Orders')),
                ('person', models.ManyToManyField(default=0, to='Employ.Person')),
            ],
            options={
                'verbose_name': 'اتصال ایستگاه و پرسنل به سفارش',
                'verbose_name_plural': 'اتصال ایستگاه و پرسنل به سفارش',
            },
        ),
        migrations.CreateModel(
            name='OpcDefualt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان OPC ')),
                ('ConstructionProcesses', models.ManyToManyField(to='TRACING.Construction_processes', verbose_name='دستور ساخت ')),
            ],
            options={
                'verbose_name': 'دستور ساخت ',
                'verbose_name_plural': 'دستور ساخت ها ',
            },
        ),
        migrations.CreateModel(
            name='Opc_To_Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='مدیریت کاربرات در خط تولید ')),
                ('Date', django_jalali.db.models.jDateTimeField(verbose_name='زمان و تاریخ')),
                ('Operator', models.ManyToManyField(to='Employ.Person', verbose_name='پرسنل')),
                ('opc', models.ManyToManyField(to='TRACING.OpcDefualt', verbose_name='دستور ساخت ')),
                ('station', models.ManyToManyField(to='TRACING.Station', verbose_name='ایستگاه کاری')),
            ],
            options={
                'verbose_name': ' فریایند دستور ساخت ',
                'verbose_name_plural': ' فریایند های دستور ساخت  ',
            },
        ),
        migrations.CreateModel(
            name='Opc_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان', max_length=20, verbose_name='عنوان')),
                ('Opc_Order', models.FileField(blank=True, null=True, upload_to=TRACING.models.upload_image_path, verbose_name='فایل مدیریت پرسنل')),
                ('Instructions', models.FileField(null=True, upload_to=TRACING.models.upload_image_path, verbose_name='دستورالعمل ساخت ')),
                ('picture', models.ImageField(null=True, upload_to=TRACING.models.upload_image_path, verbose_name='عکس محصول')),
                ('time', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='روز ثبت ')),
                ('date', models.TimeField(blank=True, null=True, verbose_name='زمان ثبت ')),
                ('Order_code_Product', models.ManyToManyField(to='TRACING.Orders', verbose_name=' OPC مربوط به کد سفارش ')),
                ('Product', models.ManyToManyField(to='INV.Product', verbose_name=' محصول ')),
            ],
            options={
                'verbose_name': 'OPC',
                'verbose_name_plural': 'فرایندها',
            },
        ),
        migrations.CreateModel(
            name='Device_Connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان')),
                ('Data', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='روز اتصال')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='زمان اتصال')),
                ('Operators', models.ManyToManyField(blank=True, to='Employ.Person', verbose_name='کد پرسنلی')),
                ('Stations', models.ManyToManyField(to='TRACING.Station', verbose_name='شماره ایستگاه ')),
            ],
            options={
                'verbose_name': 'ایستگاه متصل شده ',
                'verbose_name_plural': 'ایستگاهای متصل شده ',
            },
        ),
    ]
