# Generated by Django 3.2.9 on 2022-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='StationNumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
