# Generated by Django 3.2.9 on 2022-01-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0002_alter_station_stationnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opc_to_stations',
            name='opc',
        ),
    ]
