# Generated by Django 3.2.9 on 2022-01-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0006_auto_20220105_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opc_to_stations',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
