# Generated by Django 3.2.9 on 2022-01-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0007_alter_opc_to_stations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='opc_To_stations',
            field=models.ManyToManyField(to='TRACING.Opc_To_Stations'),
        ),
    ]
