# Generated by Django 3.2.9 on 2022-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0008_orders_opc_to_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='opc_To_stations',
            field=models.ManyToManyField(to='TRACING.Opc_To_Stations', verbose_name='دستور ساخت و استگاه '),
        ),
    ]
