# Generated by Django 3.2.9 on 2022-01-11 13:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0009_alter_orders_opc_to_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opc_to_stations',
            name='Date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان و تاریخ'),
        ),
    ]
