# Generated by Django 3.2.9 on 2022-01-12 08:34

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0010_alter_opc_to_stations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=20, null=True, verbose_name='ایستگاه')),
                ('tracebilityCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ردیابی')),
                ('Date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='زمان')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='Connected',
            field=models.BooleanField(default=False, verbose_name='اتصال شده '),
        ),
    ]
