# Generated by Django 3.2.9 on 2022-01-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0011_auto_20220112_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unknownoperator',
            options={'verbose_name': 'اپراتور ناشناخته', 'verbose_name_plural': ' جدول اپراتور های  ناشناخته '},
        ),
    ]
