# Generated by Django 3.2.9 on 2022-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0012_alter_unknownoperator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt_out',
            name='description_prodact',
            field=models.TextField(default=True, max_length=250, verbose_name='شرح قطعه'),
        ),
        migrations.AlterField(
            model_name='recipt_out',
            name='form_number',
            field=models.CharField(blank=True, default=True, max_length=10, verbose_name='شماره حواله'),
        ),
        migrations.AlterField(
            model_name='sum_recipt_out',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=200, verbose_name='شرح'),
        ),
    ]
