# Generated by Django 3.2.9 on 2022-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0014_auto_20220116_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt_out',
            name='Cod_Operator',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد اپراتور'),
        ),
        migrations.AlterField(
            model_name='recipt_out',
            name='curent_data',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ '),
        ),
    ]
