# Generated by Django 3.2.9 on 2022-01-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0015_auto_20220116_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opc_to_stations',
            options={'verbose_name': 'ثبت دستورساخت ها نسبت به هر استگاه ', 'verbose_name_plural': 'جدول ثبت دستورساخت ها نسبت به هر استگاه'},
        ),
        migrations.AlterModelOptions(
            name='tracebilitycode',
            options={'verbose_name': 'کد های ردیابی تولید شده ', 'verbose_name_plural': ' جدول کد های ردیابی تولید شده'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='opc_To_stations',
        ),
    ]
