# Generated by Django 3.2.9 on 2022-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0016_auto_20220120_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opc_to_stations',
            options={'verbose_name': ' ثبت دستورساخت ها نسبت به هر استگاه ', 'verbose_name_plural': 'جدول ثبت دستورساخت ها نسبت به هر استگاه'},
        ),
        migrations.AddField(
            model_name='orders',
            name='opc_To_stations',
            field=models.ManyToManyField(to='TRACING.Opc_To_Stations', verbose_name='دستور ساخت و استگاه '),
        ),
    ]
