# Generated by Django 3.2.9 on 2022-01-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0017_auto_20220120_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracebilitydata_2',
            options={'verbose_name': ' کد ردیابی ذخیره شده ', 'verbose_name_plural': ' جدول ردیابی کد های ذخیره شده  '},
        ),
        migrations.RemoveField(
            model_name='construction_processes',
            name='code',
        ),
        migrations.RemoveField(
            model_name='construction_processes',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='opc_to_stations',
            name='Instructions1',
        ),
        migrations.RemoveField(
            model_name='opc_to_stations',
            name='Instructions2',
        ),
    ]
