# Generated by Django 3.2.9 on 2022-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0018_auto_20220122_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcdefualt',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان OPC '),
        ),
    ]
