# Generated by Django 3.2.9 on 2022-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0019_alter_opcdefualt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='opc_to_stations',
            name='opc',
            field=models.ManyToManyField(to='TRACING.OpcDefualt', verbose_name='دستور ساخت '),
        ),
    ]
