# Generated by Django 3.2.9 on 2022-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0020_opc_to_stations_opc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opc_to_stations',
            name='opc',
            field=models.ManyToManyField(to='TRACING.Construction_processes', verbose_name='دستور ساخت '),
        ),
    ]
