# Generated by Django 3.2.9 on 2022-01-22 18:15

import TRACING.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0021_alter_opc_to_stations_opc'),
    ]

    operations = [
        migrations.AddField(
            model_name='opc_to_stations',
            name='Instructions1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=TRACING.models.upload_image_path, verbose_name='دستورالعمل ساخت 1'),
        ),
        migrations.AddField(
            model_name='opc_to_stations',
            name='Instructions2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=700, size=[600, 700], upload_to=TRACING.models.upload_image_path, verbose_name='دستورالعمل ساخت 2'),
        ),
    ]
