# Generated by Django 3.2.9 on 2022-01-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0022_auto_20220122_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='opc_To_stations',
        ),
    ]
