# Generated by Django 3.2.9 on 2022-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0023_remove_orders_opc_to_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='opc_To_stations',
            field=models.ManyToManyField(to='TRACING.Opc_To_Stations', verbose_name='دستور ساخت و استگاه '),
        ),
    ]
