# Generated by Django 3.2.9 on 2022-02-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0024_orders_opc_to_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt_out',
            name='code_Tracebility',
            field=models.IntegerField(default=True, verbose_name='کد ردیابی'),
        ),
    ]
