# Generated by Django 3.2.9 on 2022-02-28 11:17

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0025_recipt_out_code_tracebility'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator', models.CharField(blank=True, max_length=40, verbose_name='اپراتور')),
                ('Station', models.CharField(blank=True, max_length=40, verbose_name='ایسنگاه')),
                ('Order', models.CharField(blank=True, max_length=40, verbose_name='سفارش')),
                ('Entery', models.CharField(blank=True, max_length=40, verbose_name='ورودی های ایستگاه تعمیرات ')),
                ('Product', models.CharField(blank=True, max_length=40, verbose_name='محصول')),
                ('tracebilityCode', models.CharField(blank=True, max_length=40, verbose_name='کد ردیابی')),
                ('Date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('Time', models.TimeField(blank=True, null=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'تعمیرات',
                'verbose_name_plural': ' جدول محصولات تعمیر شده',
            },
        ),
        migrations.AddField(
            model_name='unknownoperator',
            name='Order',
            field=models.CharField(blank=True, max_length=40, verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='unknownoperator',
            name='Product',
            field=models.CharField(blank=True, max_length=40, verbose_name='محصول'),
        ),
    ]
