# Generated by Django 3.2.9 on 2022-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0027_auto_20220228_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairstation',
            name='Enter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='repairstation',
            name='Exit',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
