# Generated by Django 3.2.9 on 2022-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0029_remove_repairstation_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairstation',
            name='State',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Entery',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ورودی های ایستگاه تعمیرات '),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Exit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Operator',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Order',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Product',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='Station',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ایسنگاه'),
        ),
    ]
