# Generated by Django 3.2.9 on 2022-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRACING', '0031_repairstation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairstation',
            name='Cuase',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='repairstation',
            name='State',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
