# Generated by Django 3.2.9 on 2022-04-26 08:28

import FileManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام ')),
                ('File', models.FileField(blank=True, null=True, upload_to=FileManager.models.upload_App_path, verbose_name='File')),
                ('version', models.FloatField(blank=True, null=True, verbose_name='ورژن')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
