# Generated by Django 3.2.9 on 2021-12-17 14:01

import Employ.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizational_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان', max_length=20, verbose_name='عنوان')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='نام ')),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'چارت سازمانی ',
                'verbose_name_plural': '  چارت سازمانی پرسنل ها',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان', max_length=20, verbose_name='عنوان')),
                ('Name', models.CharField(max_length=30, verbose_name='نام ')),
                ('LastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('Age', models.CharField(blank=True, max_length=5, verbose_name='سن')),
                ('TelephonNumber', models.CharField(blank=True, default=0, max_length=20, verbose_name='شماره تلفن')),
                ('Address', models.TextField(blank=True, verbose_name='ادرس')),
                ('CodeOperator', models.IntegerField(unique=True, verbose_name='کد پرسنلی')),
                ('StartBarcode', models.CharField(default=1, max_length=7, unique=True, verbose_name='کد شروع')),
                ('StopBarcode', models.CharField(default=0, max_length=7, unique=True, verbose_name='کد  پایان')),
                ('Image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=200, size=[100, 120], upload_to=Employ.models.upload_image_path, verbose_name='عکس پرسنل ')),
                ('Start', models.BooleanField(blank=True, null=True, verbose_name='وضعیت فعال')),
                ('OrChart', models.ManyToManyField(to='Employ.Organizational_chart', verbose_name='چارت سازمانی ')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل ها',
            },
        ),
    ]
