# Generated by Django 3.2.9 on 2021-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='ورژن '),
        ),
    ]
