# Generated by Django 3.2.9 on 2021-12-26 13:25

import DetailApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0002_appdetail_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام اپلیکشن ')),
                ('App', models.FileField(blank=True, null=True, upload_to=DetailApp.models.upload_App_path, verbose_name='فایل نرم افزار کلاینت ردیابی')),
            ],
        ),
    ]
