# Generated by Django 3.2.9 on 2021-12-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0003_clientapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='version',
            field=models.FloatField(blank=True, null=True, verbose_name='ورژن'),
        ),
    ]
