# Generated by Django 3.2.9 on 2021-12-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0004_clientapp_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='Active',
            field=models.BooleanField(blank=True, null=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
