# Generated by Django 3.2.9 on 2022-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0005_auto_20211227_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='BarcodeRestart',
            field=models.CharField(default='1', max_length=12),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='BarcodeShutdown',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='DataBase_Address',
            field=models.GenericIPAddressField(default='192.168.4.51'),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='DataBase_Name',
            field=models.CharField(default='photon', max_length=20),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='DatabasePort',
            field=models.CharField(default='5432', max_length=6),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='PASSWORD_SERVER',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='Server_Address',
            field=models.GenericIPAddressField(default='192.168.4.50'),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='USER_SERVER',
            field=models.CharField(default='shaho', max_length=50),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='send_port',
            field=models.CharField(default='8000', max_length=6, verbose_name='PortServer'),
        ),
    ]
