# Generated by Django 3.2.9 on 2022-01-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0006_auto_20220108_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='BarcodeRestart',
            field=models.CharField(default='1154654166', max_length=12),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='BarcodeShutdown',
            field=models.CharField(default='0012546879', max_length=12),
        ),
        migrations.AlterField(
            model_name='clientapp',
            name='PASSWORD_SERVER',
            field=models.CharField(default='aezakmiHESOYAMFu$!on-123', max_length=50),
        ),
    ]
