# Generated by Django 3.2.9 on 2022-01-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0007_auto_20220108_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='BarcodeShutdown',
            field=models.CharField(default='1254687900', max_length=12),
        ),
    ]
