# Generated by Django 3.2.9 on 2022-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0008_alter_clientapp_barcodeshutdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='BarcodeRestart',
            field=models.CharField(default='5465406611', max_length=12),
        ),
    ]
