# Generated by Django 3.2.9 on 2022-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailApp', '0009_alter_clientapp_barcoderestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='BarcodeProdocer',
            field=models.CharField(default='5554687910', max_length=12),
        ),
        migrations.AddField(
            model_name='clientapp',
            name='BarcodeRepair',
            field=models.CharField(default='7654687920', max_length=12),
        ),
    ]
