# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QApplication
import sys

class Ui_Dialog_Delete(object):
    def setupUi(self, Dialog_Delete):
        Dialog_Delete.setObjectName("Dialog_Delete")
        Dialog_Delete.resize(478, 359)
        self.lineEdit = QtWidgets.QLineEdit(Dialog_Delete)
        self.lineEdit.setGeometry(QtCore.QRect(200, 130, 111, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog_Delete)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 50, 111, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog_Delete)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 90, 111, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(Dialog_Delete)
        self.label.setGeometry(QtCore.QRect(350, 50, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_Delete)
        self.label_2.setGeometry(QtCore.QRect(350, 90, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_Delete)
        self.label_3.setGeometry(QtCore.QRect(350, 130, 111, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog_Delete)
        self.pushButton.setGeometry(QtCore.QRect(370, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog_Delete)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Delete)

    def retranslateUi(self, Dialog_Delete):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Delete.setWindowTitle(_translate("Dialog_Delete", "Dialog"))
        self.label.setText(_translate("Dialog_Delete", "نام محصول "))
        self.label_2.setText(_translate("Dialog_Delete", "کد محصول "))
        self.label_3.setText(_translate("Dialog_Delete", "کد ردیابی"))
        self.pushButton.setText(_translate("Dialog_Delete", "پاک کردن "))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    # app.setStyle("Fusion")
    Dialog_Delete  = QtWidgets.QWidget()
    ui  = Ui_Dialog_Delete()
    ui.setupUi(Dialog_Delete)
    Dialog_Delete.show()
    sys.exit(app.exec_())


