# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import  Server.Server_Gui_Bpms_30
from Server.OPC_Managment  import   Manager_OPC_23_Withe
from  Server import    Setting_server

# Server.Reporter_Tracebility_04, Server.OPC_Managment.Manager_OPC_22_Withe
from  PyQt5.uic import loadUi


class Ui_Main(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Main, self).__init__()
        loadUi("D:/photon_project/Tracebility_01/venv_new/Server/Main.ui", self)
        # self.pushButton_Server.clicked.connect(self.start_server)
        # OPC_UI = Manager_OPC_22_Withe.OPC_UI_MainWindow()
        # OPC_Widget = QtWidgets.QMainWindow()
        # OPC_UI.setupUi(OPC_Widget)
        # self.pushButton_OPC_Manage.clicked.connect(lambda: OPC_Widget.show())

    def start_server(self):
        print("start_server")

    def start_opc(self):
        print("start_opc")







    # def setupUi(self, Main):
    #     Main.setObjectName("Main")
    #     Main.resize(817, 594)
    #     self.centralwidget = QtWidgets.QWidget(Main)
    #     self.centralwidget.setObjectName("centralwidget")
    #     self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
    #     self.gridLayout.setObjectName("gridLayout")
    #     self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
    #     self.groupBox.setTitle("")
    #     self.groupBox.setObjectName("groupBox")
    #     self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
    #     self.pushButton_4.setGeometry(QtCore.QRect(420, 270, 371, 261))
    #     self.pushButton_4.setObjectName("pushButton_4")
    #     self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
    #     self.pushButton_5.setGeometry(QtCore.QRect(10, 270, 370, 370))
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
    #     self.pushButton_5.setSizePolicy(sizePolicy)
    #     self.pushButton_5.setMinimumSize(QtCore.QSize(370, 260))
    #     self.pushButton_5.setMaximumSize(QtCore.QSize(370, 260))
    #     self.pushButton_5.setObjectName("pushButton_5")
    #     self.pushButton_Server = QtWidgets.QPushButton(self.groupBox)
    #     self.pushButton_Server.setGeometry(QtCore.QRect(10, 0, 371, 261))
    #     self.pushButton_Server.setObjectName("pushButton_Server")
    #     self.pushButton_OPC_Manage = QtWidgets.QPushButton(self.groupBox)
    #     self.pushButton_OPC_Manage.setGeometry(QtCore.QRect(420, 0, 371, 261))
    #     self.pushButton_OPC_Manage.setObjectName("pushButton_OPC_Manage")
    #     self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
    #     Main.setCentralWidget(self.centralwidget)
    #     self.menubar = QtWidgets.QMenuBar(Main)
    #     self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
    #     self.menubar.setObjectName("menubar")
    #     Main.setMenuBar(self.menubar)
    #     self.statusbar = QtWidgets.QStatusBar(Main)
    #     self.statusbar.setObjectName("statusbar")
    #     Main.setStatusBar(self.statusbar)
    #
    #     self.retranslateUi(Main)
    #     QtCore.QMetaObject.connectSlotsByName(Main)
    #
    # def retranslateUi(self, Main):
    #     _translate = QtCore.QCoreApplication.translate
    #     Main.setWindowTitle(_translate("Main", "MainWindow"))
    #     self.pushButton_4.setText(_translate("Main", "Inventory"))
    #     self.pushButton_5.setText(_translate("Main", "Reporter "))
    #     self.pushButton_Server.setText(_translate("Main", "Server Tracebility"))
    #     self.pushButton_OPC_Manage.setText(_translate("Main", "OPC_Managment"))



import sys

# import sys
app_main = QtWidgets.QApplication(sys.argv)
main_window = Ui_Main()
main_widget =  QtWidgets.QStackedWidget()
main_widget.addWidget(main_window)

main_widget.setFixedHeight(600)
main_widget.setFixedWidth(800)


#
Server_app1 =  QtWidgets.QApplication(sys.argv)
Server_MainWindow1 = QtWidgets.QMainWindow()
ui1 =  Server.Server_Gui_Bpms_30.Ui_Main_Server()
ui1.setupUi(Server_MainWindow1)
main_window.pushButton_Server.clicked.connect(lambda : Server_MainWindow1.show() )

# OPC_APP   = QtWidgets.QApplication(sys.argv)
OPC_UI = Manager_OPC_23_Withe.OPC_UI_MainWindow()
OPC_Widget = QtWidgets.QMainWindow()
OPC_UI.setupUi(OPC_Widget)
main_window.pushButton_OPC_Manage.clicked.connect(lambda: OPC_Widget.show())

Setting_UI = Setting_server.Ui_Setting_Network()
Setting_widget =  QtWidgets.QWidget()
Setting_UI.setupUi(Setting_widget)

OPC_UI.actionNetwork_Setting.triggered.connect(lambda: Setting_widget.show())



# sys.exit(app_main.exec_())
if __name__ == "__main__":
    import sys

    Main_app = QtWidgets.QApplication(sys.argv)
    main_window_ui = Ui_Main()
    main_widget =  QtWidgets.QStackedWidget()
    main_widget.addWidget(main_window_ui)
    main_widget.show()
    main_widget.setFixedHeight(600)
    main_widget.setFixedWidth(800)
    # ########################
    #
    # Server_UI =  Server.Server_Gui_Bpms_30.Ui_Main_Server()
    # Server_Windows = QtWidgets.QMainWindow()
    # Server_UI.setupUi(Server_Windows)
    # main_window_ui.pushButton_Server.clicked.connect(lambda : Server_Windows.show() )

    OPC_UI = Manager_OPC_23_Withe.OPC_UI_MainWindow()
    OPC_Widget = QtWidgets.QMainWindow()
    OPC_UI.setupUi(OPC_Widget)
    main_window_ui.pushButton_OPC_Manage.clicked.connect(lambda: OPC_Widget.show())

    Setting_UI = Setting_server.Ui_Setting_Network()
    Setting_widget = QtWidgets.QWidget()
    Setting_UI.setupUi(Setting_widget)

    OPC_UI.actionNetwork_Setting.triggered.connect(lambda: Setting_widget.show())

    sys.exit(Main_app.exec_())










