# Generated by Django 3.2.9 on 2021-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('name', models.CharField(max_length=150, verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها ',
            },
        ),
    ]
